const courses = [
    { value: 'Abi Ciências Sociais - Noturno', label:'Abi Ciências Sociais - Noturno'},
    { value: 'Abi Ciências Sociais - Vespertino', label:'Abi Ciências Sociais - Vespertino'},
    { value: 'Abi Filosofia - Noturno', label:'Abi Filosofia - Noturno'},
    { value: 'Abi Filosofia - Vespertino', label:'Abi Filosofia - Vespertino'},
    { value: 'Abi Geografia - Matutino', label:'Abi Geografia - Matutino'},
    { value: 'Abi História - Noturno', label:'Abi História - Noturno'},
    { value: 'Abi História - Vespertino', label:'Abi História - Vespertino'},
    { value: 'Abi Letras Português - Noturno', label:'Abi Letras Português - Noturno'},
    { value: 'Abi Letras Português - Vespertino', label:'Abi Letras Português - Vespertino'},
    { value: 'Abi Letras Português-Espanhol - Noturno', label:'Abi Letras Português-Espanhol - Noturno'},
    { value: 'Abi Letras Português-Espanhol - Vespertino', label:'Abi Letras Português-Espanhol - Vespertino'},
    { value: 'Abi Letras Português-Francês - Noturno', label:'Abi Letras Português-Francês - Noturno'},
    { value: 'Abi Letras Português-Francês - Vespertino', label:'Abi Letras Português-Francês - Vespertino'},
    { value: 'Abi Letras Português-Inglês - Noturno', label:'Abi Letras Português-Inglês - Noturno'},
    { value: 'Abi Letras Português-Inglês - Vespertino', label:'Abi Letras Português-Inglês - Vespertino'},
    { value: 'Administração - Integral', label:'Administração - Integral'},
    { value: 'Administração - Noturno', label:'Administração - Noturno'},
    { value: 'Alimentos, Nutrição e Saúde', label:'Alimentos, Nutrição e Saúde'},
    { value: 'Análise Ambiental Integrada', label:'Análise Ambiental Integrada'},
    { value: 'Biodiversidade e Ecologia Marinha e Costeira', label:'Biodiversidade e Ecologia Marinha e Costeira'},
    { value: 'Biologia Estrutural e Funcional', label:'Biologia Estrutural e Funcional'},
    { value: 'Biologia Química', label:'Biologia Química'},
    { value: 'Biomedicina - Integral', label:'Biomedicina - Integral'},
    { value: 'Bioprodutos e Bioprocessos', label:'Bioprodutos e Bioprocessos'},
    // { value: 'Biotecnologia - Integral', label:'Biotecnologia - Integral'},
    { value: 'Biotecnologia', label:'Biotecnologia'},
    { value: 'Ciência Cirúrgica Interdisciplinar', label:'Ciência Cirúrgica Interdisciplinar'},
    // { value: 'Ciência Da Computação - Integral', label:'Ciência Da Computação - Integral'},
    { value: 'Ciência da Computação', label:'Ciência da Computação'},
    { value: 'Ciência e Tecnologia da Sustentabilidade', label:'Ciência e Tecnologia da Sustentabilidade'},
    { value: 'Ciência, Tecnologia e Gestão Aplicadas à Regeneração Tecidual', label:'Ciência, Tecnologia e Gestão Aplicadas à Regeneração Tecidual'},
    { value: 'Ciências - Noturno', label:'Ciências - Noturno'},
    { value: 'Ciências - Vespertino', label:'Ciências - Vespertino'},
    { value: 'Ciências Ambientais - Integral', label:'Ciências Ambientais - Integral'},
    { value: 'Ciências Atuariais - Integral', label:'Ciências Atuariais - Integral'},
    { value: 'Ciências Atuariais - Noturno', label:'Ciências Atuariais - Noturno'},
    { value: 'Ciências Biológicas - Integral', label:'Ciências Biológicas - Integral'},
    { value: 'Ciências Biológicas Biologia Molecular', label:'Ciências Biológicas Biologia Molecular'},
    { value: 'Ciências Contábeis - Integral', label:'Ciências Contábeis - Integral'},
    { value: 'Ciências Contábeis - Noturno', label:'Ciências Contábeis - Noturno'},
    { value: 'Ciências da Saúde Aplicadas à Reumatologia', label:'Ciências da Saúde Aplicadas à Reumatologia'},
    { value: 'Ciências da Saúde Aplicadas ao Esporte e à Atividade Física', label:'Ciências da Saúde Aplicadas ao Esporte e à Atividade Física'},
    { value: 'Ciências do Movimento Humano e Reabilitação', label:'Ciências do Movimento Humano e Reabilitação'},
    { value: 'Ciências Econômicas - Integral', label:'Ciências Econômicas - Integral'},
    { value: 'Ciências Econômicas - Noturno', label:'Ciências Econômicas - Noturno'},
    { value: 'Ciências Farmacêuticas', label:'Ciências Farmacêuticas'},
    { value: 'Ciências Sociais Bacharelado - Noturno', label:'Ciências Sociais Bacharelado - Noturno'},
    { value: 'Ciências Sociais Bacharelado - Vespertino', label:'Ciências Sociais Bacharelado - Vespertino'},
    { value: 'Ciências Sociais Licenciatura - Noturno', label:'Ciências Sociais Licenciatura - Noturno'},
    { value: 'Ciências Sociais Licenciatura - Vespertino', label:'Ciências Sociais Licenciatura - Vespertino'},
    { value: 'Ciências Sociais', label:'Ciências Sociais'},
    { value: 'Cirurgia Translacional', label:'Cirurgia Translacional'},
    { value: 'Curso Superior De Tecnologia Em Design Educacional', label:'Curso Superior De Tecnologia Em Design Educacional'},
    { value: 'Curso Superior De Tecnologia Em Informática Em Saúde - Matutino', label:'Curso Superior De Tecnologia Em Informática Em Saúde - Matutino'},
    { value: 'Curso Superior De Tecnologia Em Radiologia - Integral', label:'Curso Superior De Tecnologia Em Radiologia - Integral'},
    { value: 'Curso Superior De Tecnologia Oftálmica - Integral', label:'Curso Superior De Tecnologia Oftálmica - Integral'},
    { value: 'Curso Superior De Tecnologia Oftálmica - Matutino', label:'Curso Superior De Tecnologia Oftálmica - Matutino'},
    { value: 'Direito - Integral', label:'Direito - Integral'},
    { value: 'Distúrbios da Comunicação Humana/Fonoaudiologia', label:'Distúrbios da Comunicação Humana/Fonoaudiologia'},
    { value: 'Ecologia e Evolução', label:'Ecologia e Evolução'},
    { value: 'Economia e Desenvolvimento', label:'Economia e Desenvolvimento'},
    { value: 'Educação e Saúde na Infância e na Adolescência', label:'Educação e Saúde na Infância e na Adolescência'},
    { value: 'Educação Física - Integral', label:'Educação Física - Integral'},
    { value: 'Educação', label:'Educação'},
    { value: 'Enfermagem - Bacharel - Integral', label:'Enfermagem - Bacharel - Integral'},
    { value: 'Enfermagem', label:'Enfermagem'},
    { value: 'Engenharia Ambiental - Noturno', label:'Engenharia Ambiental - Noturno'},
    // { value: 'Engenharia Biomédica - Integral', label:'Engenharia Biomédica - Integral'},
    { value: 'Engenharia Biomédica', label:'Engenharia Biomédica'},
    // { value: 'Engenharia De Computação - Integral', label:'Engenharia De Computação - Integral'},
    { value: 'Engenharia De Computação', label:'Engenharia De Computação'},
    // { value: 'Engenharia De Materiais - Integral', label:'Engenharia De Materiais - Integral'},
    { value: 'Engenharia De Materiais', label:'Engenharia De Materiais'},
    { value: 'Engenharia De Petróleo - Integral', label:'Engenharia De Petróleo - Integral'},
    { value: 'Engenharia De Petróleo - Noturno', label:'Engenharia De Petróleo - Noturno'},
    { value: 'Engenharia e Ciência de Materiais', label:'Engenharia e Ciência de Materiais'},
    { value: 'Engenharia Química - Integral', label:'Engenharia Química - Integral'},
    { value: 'Engenharia Química - Noturno', label:'Engenharia Química - Noturno'},
    { value: 'Engenharia Química', label:'Engenharia Química'},
    { value: 'Ensino de Ciências e Matemática', label:'Ensino de Ciências e Matemática'},
    { value: 'Ensino de História', label:'Ensino de História'},
    { value: 'Ensino em Ciência da Saúde', label:'Ensino em Ciência da Saúde'},
    { value: 'Farmácia - Integral', label:'Farmácia - Integral'},
    { value: 'Farmácia - Noturno', label:'Farmácia - Noturno'},
    { value: 'Farmacologia', label:'Farmacologia'},
    { value: 'Filosofia Bacharelado - Noturno', label:'Filosofia Bacharelado - Noturno'},
    { value: 'Filosofia Bacharelado - Vespertino', label:'Filosofia Bacharelado - Vespertino'},
    { value: 'Filosofia Licenciatura - Noturno', label:'Filosofia Licenciatura - Noturno'},
    { value: 'Filosofia Licenciatura - Vespertino', label:'Filosofia Licenciatura - Vespertino'},
    { value: 'Filosofia', label:'Filosofia'},
    { value: 'Fisioterapia - Integral', label:'Fisioterapia - Integral'},
    { value: 'Fonoaudiologia - Integral', label:'Fonoaudiologia - Integral'},
    { value: 'Gastroenterologia', label:'Gastroenterologia'},
    { value: 'Geografia Bacharelado Matutino', label:'Geografia Bacharelado Matutino'},
    { value: 'Geografia Licenciatura Matutino', label:'Geografia Licenciatura Matutino'},
    { value: 'Gestão de Políticas e Organizações Públicas', label:'Gestão de Políticas e Organizações Públicas'},
    { value: 'Gestão e Informática em Saúde', label:'Gestão e Informática em Saúde'},
    { value: 'História Bacharelado - Noturno', label:'História Bacharelado - Noturno'},
    { value: 'História Bacharelado - Vespertino', label:'História Bacharelado - Vespertino'},
    { value: 'História Da Arte - Noturno', label:'História Da Arte - Noturno'},
    { value: 'História da Arte', label:'História da Arte'},
    { value: 'História Licenciatura - Noturno', label:'História Licenciatura - Noturno'},
    { value: 'História Licenciatura - Vespertino', label:'História Licenciatura - Vespertino'},
    { value: 'História', label:'História'},
    { value: 'Infectologia', label:'Infectologia'},
    { value: 'Inovação Tecnológica', label:'Inovação Tecnológica'},
    // { value: 'Interdisciplinar Em Ciência E Tecnologia - Integral', label:'Interdisciplinar Em Ciência E Tecnologia - Integral'},
    // { value: 'Interdisciplinar Em Ciência E Tecnologia - Noturno', label:'Interdisciplinar Em Ciência E Tecnologia - Noturno'},
    { value: 'Interdisciplinar Em Ciência E Tecnologia', label:'Interdisciplinar Em Ciência E Tecnologia'},
    { value: 'Interdisciplinar Em Ciência E Tecnologia Do Mar - Noturno', label:'Interdisciplinar Em Ciência E Tecnologia Do Mar - Noturno'},
    { value: 'Interdisciplinar Em Ciência E Tecnologia Do Mar - Vespertino', label:'Interdisciplinar Em Ciência E Tecnologia Do Mar - Vespertino'},
    { value: 'Interdisciplinar em Ciências da Saúde', label:'Interdisciplinar em Ciências da Saúde'},
    { value: 'Letras - Português (Bacharelado) - Noturno', label:'Letras - Português (Bacharelado) - Noturno'},
    { value: 'Letras - Português (Bacharelado) - Vespertino', label:'Letras - Português (Bacharelado) - Vespertino'},
    { value: 'Letras - Português (Licenciatura) - Noturno', label:'Letras - Português (Licenciatura) - Noturno'},
    { value: 'Letras - Português (Licenciatura) - Vespertino', label:'Letras - Português (Licenciatura) - Vespertino'},
    { value: 'Letras - Português E Espanhol (Bacharelado) - Noturno', label:'Letras - Português E Espanhol (Bacharelado) - Noturno'},
    { value: 'Letras - Português E Espanhol (Bacharelado) - Vespertino', label:'Letras - Português E Espanhol (Bacharelado) - Vespertino'},
    { value: 'Letras - Português E Espanhol (Licenciatura) - Noturno', label:'Letras - Português E Espanhol (Licenciatura) - Noturno'},
    { value: 'Letras - Português E Espanhol (Licenciatura) - Vespertino', label:'Letras - Português E Espanhol (Licenciatura) - Vespertino'},
    { value: 'Letras - Português E Francês (Bacharelado) - Noturno', label:'Letras - Português E Francês (Bacharelado) - Noturno'},
    { value: 'Letras - Português E Francês (Bacharelado) - Vespertino', label:'Letras - Português E Francês (Bacharelado) - Vespertino'},
    { value: 'Letras - Português E Francês (Licenciatura) - Noturno', label:'Letras - Português E Francês (Licenciatura) - Noturno'},
    { value: 'Letras - Português E Francês (Licenciatura) - Vespertino', label:'Letras - Português E Francês (Licenciatura) - Vespertino'},
    { value: 'Letras - Português E Inglês (Bacharelado) - Noturno', label:'Letras - Português E Inglês (Bacharelado) - Noturno'},
    { value: 'Letras - Português E Inglês (Bacharelado) - Vespertino', label:'Letras - Português E Inglês (Bacharelado) - Vespertino'},
    { value: 'Letras - Português E Inglês (Licenciatura) - Noturno', label:'Letras - Português E Inglês (Licenciatura) - Noturno'},
    { value: 'Letras - Português E Inglês (Licenciatura) - Vespertino', label:'Letras - Português E Inglês (Licenciatura) - Vespertino'},
    { value: 'Letras', label:'Letras'},
    { value: 'Licenciatura Intercultural Indígena', label:'Licenciatura Intercultural Indígena'},
    { value: 'Matemática Aplicada', label:'Matemática Aplicada'},
    // { value: 'Matemática Computacional - Integral', label:'Matemática Computacional - Integral'},
    { value: 'Matemática Computacional', label:'Matemática Computacional'},
    { value: 'Matemática em Rede Nacional (ProfMat)', label:'Matemática em Rede Nacional (ProfMat)'},
    { value: 'Medicina - Integral', label:'Medicina - Integral'},
    { value: 'Medicina Cardiologia', label:'Medicina Cardiologia'},
    { value: 'Medicina Translacional', label:'Medicina Translacional'},
    { value: 'Medicina/Endocrinologia Clínica', label:'Medicina/Endocrinologia Clínica'},
    { value: 'Medicina/Ginecologia', label:'Medicina/Ginecologia'},
    { value: 'Medicina/Hematologia', label:'Medicina/Hematologia'},
    { value: 'Medicina/Nefrologia', label:'Medicina/Nefrologia'},
    { value: 'Medicina/Obstetrícia', label:'Medicina/Obstetrícia'},
    { value: 'Medicina/Otorrinolaringologia', label:'Medicina/Otorrinolaringologia'},
    { value: 'Medicina/Pneumologia', label:'Medicina/Pneumologia'},
    { value: 'Medicina/Radiologia Clínica', label:'Medicina/Radiologia Clínica'},
    { value: 'Medicina/Urologia', label:'Medicina/Urologia'},
    { value: 'Microbiologia e Imunologia', label:'Microbiologia e Imunologia'},
    { value: 'Neurologia/Neurociências', label:'Neurologia/Neurociências'},
    { value: 'Nutrição - Integral', label:'Nutrição - Integral'},
    { value: 'Nutrição', label:'Nutrição'},
    { value: 'Oceanografia', label:'Oceanografia'},
    { value: 'Oftalmologia e Ciências Visuais', label:'Oftalmologia e Ciências Visuais'},
    { value: 'Patologia', label:'Patologia'},
    { value: 'Pedagogia - Noturno', label:'Pedagogia - Noturno'},
    { value: 'Pedagogia - Vespertino', label:'Pedagogia - Vespertino'},
    { value: 'Pediatria e Ciências Aplicadas à Pediatria', label:'Pediatria e Ciências Aplicadas à Pediatria'},
    { value: 'Pesquisa Operacional', label:'Pesquisa Operacional'},
    { value: 'Psicobiologia', label:'Psicobiologia'},
    { value: 'Psicologia - Integral', label:'Psicologia - Integral'},
    { value: 'Psiquiatria e Psicologia Médica', label:'Psiquiatria e Psicologia Médica'},
    { value: 'Química - Integral', label:'Química - Integral'},
    { value: 'Química Industrial - Noturno', label:'Química Industrial - Noturno'},
    { value: 'Relações Internacionais - Integral', label:'Relações Internacionais - Integral'},
    { value: 'Relações Internacionais - Noturno', label:'Relações Internacionais - Noturno'},
    { value: 'Saúde Baseada em Evidências', label:'Saúde Baseada em Evidências'},
    { value: 'Saúde Coletiva', label:'Saúde Coletiva'},
    { value: 'Serviço Social - Noturno', label:'Serviço Social - Noturno'},
    { value: 'Serviço Social - Vespertino', label:'Serviço Social - Vespertino'},
    { value: 'Serviço Social e Políticas Sociais', label:'Serviço Social e Políticas Sociais'},
    { value: 'Tecnologias e Atenção à Saúde', label:'Tecnologias e Atenção à Saúde'},
    { value: 'Terapia Ocupacional - Integral', label:'Terapia Ocupacional - Integral'}    
];

export default courses;
